apiVersion: v1
kind: pod
metadata:
  name: nginx-pod-demo-configmap
  namespace: nginx
spec:
  containers:
    - name: nginx-demo
      image: nginx
      volumeMounts:
      - name: test-vol
        mountPath: /etc/config-map-data
        readOnly: true
  volumes:
    - name: test-vol
      configMap:
        name: demo-configmap
        items:
        - key: test_file_1.txt
          path: test_file_1.txt
        - key: test_file_2.txt
          path: test_file_2.txt