apiVersion: v1
kind: Pod
metadata:
  name: pod-demo-configmap
  namespace: default
spec:
  containers:
    - name: configmap-pod
      image: nginx
      volumeMounts:
      - name: demo-configmap
        mountPath: /etc/config-map-data
        readOnly: true
    - name: busybox
      image: busybox
      command: []
  volumes:
    - name: demo-configmap
      configMap:
        name: jan-cm
        items:
        - key: text_file_1.txt
          path: text_file_1.txt
        - key: text_file_2.txt
          path: text_file-2.txt