apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-html
  namespace: config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
        <head>
            <title>This is A Test</title>
        </head>
        <body>
            <h1 style="color: chocolate;">Hello Guys, I hope you are learning Service!!</h1>
            <h2>Congratulations, You Are Doing Well :-)</h2>
        </body>
    </html>
