apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: config
spec:
  type: LoadBalancer
  selector:
      app: nginx
  ports:
    - port: 80
#      targetPort: 8080
#      # Optional field
#      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
#      nodePort: 31111



